targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      floor_generator:
        options:
          database_name: ayanna_school_database
      chopper_generator:
        options:
          use_base_url: true
