name: ayanna_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  floor: ^1.5.0
  provider: ^6.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.1+1
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/ayanna_school.db
    - assets/images/
    - assets/annees_scolaires.json
    - assets/entreprises.json
    - assets/classes.json
    - assets/eleves.json
    - assets/enseignants.json
    - assets/frais.json
    - assets/frais_classes.json
    - assets/frais_scolaires.json
    - assets/paiement_frais.json
    - assets/responsables.json
    - assets/creances.json
    - assets/depenses.json
    - assets/comptes_config.json
    - assets/classes_comptables.json
    - assets/comptes_comptables.json
    - assets/ecritures_comptables.json
    - assets/exercices_comptables.json
    - assets/journaux_comptables.json
    - assets/config_ecole.json
    - assets/utilisateurs.json