name: ayanna_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  floor: ^1.5.0
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  pdf: ^3.0.0
  flutter_pdfview: ^1.4.1+1
  intl: ^0.20.2
  http: ^1.1.0
  chopper: ^8.0.0
  json_annotation: ^4.9.0
  connectivity_plus: ^7.0.0
  riverpod: ^2.6.1
  pretty_chopper_logger: ^1.3.0
  json_serializable_chopper_converter: ^1.0.0
  sqflite_common_ffi: ^2.3.6
  share_plus: ^12.0.0
  flutter_thermal_printer: ^1.2.4
  flutter_blue_plus: ^2.0.0
  permission_handler: ^12.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  chopper_generator: ^8.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/ayanna_school.db
    - assets/images/
    